apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - "../../operator"
 - host-config.yaml

images:
  - name: multi-arch-controller
    newName: quay.io/QUAY_USERNAME/multi-arch-controller
    newTag: dev
