apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-arch-controller
  namespace: multi-arch-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-arch-controller
  template:
    metadata:
      labels:
        app: multi-arch-controller
    spec:
      containers:
        - name: multi-arch-controller
          image: multi-arch-controller
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: Always
          args:
            - "--v=4"
            - "--zap-log-level=4"
            - "--zap-devel=true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      serviceAccountName: multi-arch-controller
