apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: multi-arch-controller
resources:
  - deployment.yaml
  - sa.yaml
  - rbac.yaml
  - provision-shared-host.yaml
  - openshift-specific-rbac.yaml
