apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: multi-arch-operator
resources:
  - deployment.yaml
  - sa.yaml
  - rbac.yaml
  - deploy-task.yaml
  - openshift-specific-rbac.yaml
