name: Codecov report on push to the "main" branch
on:
  push:
    branches: [ main ]
jobs:
  coverage:
    name: Unit tests and coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
        with:
          go-version-file: './go.mod'
      - name: Build
        run: make build
      - name: Run tests
        run: make test
      - name: Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3